### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by michabbb** [vickzkater/lara-s-cms#14]
hi there,

if i may ask: is it possible to send notifications based on actions, users are doing ? for example: slack ?
i know, laravel can do this, but i would like to know if the concept of hooks exist in this cms ? ;)

another important thing, at least for me, is: is there are history of each edited page ?
is there are diff view ? so others can easily check, what has changed ?

thanks a lot,
micha

**Comment by vickzkater** [comment]
Hi, Micha (michabbb).

First, I want to say thank you for your interest in this project.

Unfortunately, Lara-S-CMS doesn't support the concept of hooks for the current version. But maybe it will exist in the next version.

And about the history of each edited page, what do you mean about that? Do you mean a history of edited source code or data on that page?

Thank you,
Vicky

**Comment by michabbb** [comment]
thanks for your feedback. when talking about history, I mean the data on the page. maybe a wiki is not your intention with that project but I am not 100% happy with my dokuwiki, so I am always looking around 😏
a must have for me in that situation is:

- get notifications when someone changes a page (or creates)
- be able to see changes: a diff view (on large pages you will never find what has changed, that is awful)

that's why I am asking 😏

**Comment by vickzkater** [comment]
Sorry, for the late response.
Unfortunately, Lara-S-CMS doesn't have that feature for your needs in the current version.
Maybe I will develop that feature in the next version.
Thank you for your comment, Micha.
