### ISSUE TITLE
Add sign up 

### ISSUE THREAD

**Issue by Pix-Eb** [vickzkater/lara-s-cms#15]
Dear all, 
First of all, congratulations on your work. Great Job !!
I would like to add a Sign up process, in your opinion what's the best way ?

Congrat again ! And thx 

Fred

**Comment by vickzkater** [comment]
Hi, Fred. Thank you for your appreciation 🙏🏻
For the sign-up process, you can develop it according to your needs.
Lara-S-CMS is a project Content Management System (CMS) or Admin Dashboard - within or without a website.
If you used this project for a website that visitors can register membership, so you can develop a sign-up page on your website - not on this CMS.
